env:
    idtl: "ENCRYPTED[d90f6c7c9c1c7c2304c3792b138e366a84a07cece5cf238dcd41f81a8c393abac98ecf16a9fcf67c3ad25d91d45e8258]"
    rcloneconfig: "ENCRYPTED[7110081cd97a3828efe137a850d47d5727ac9b8afd3387a67de7896a224e17a96df6d59734c4817b7dfc88f19899ddb9]"
    tokentl: "ENCRYPTED[f4d994a3281d125c9e600605002a672b82efcb08aa44ae56f5b0829ffb057a9e079d99c54e97104c734bb5c7fedb4745]"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  timeout_in: 125m  
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Setup_script:
       - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="...Setup Build..."
       - git config --global user.name "Leon4rd"
       - git config --global user.email "38402513+leon4rd@users.noreply.github.com"
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - mkdir -p /tmp/ccache
       #- rclone copy rclonerw:dup9/ccache.tar.gz /tmp -P
       #- cd /tmp
       #- time tar xf ccache.tar.gz
       - df -h
       - lsblk
       - ls -l -a -h
       #- rm ccache.tar.gz
       - ls /tmp/ccache
       - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Setup Build Successfully!"

  Sync_script:
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="...Sync Source..."
      - mkdir -p /tmp/rom
      - cd /tmp/rom
      - repo init --depth=1 -u https://github.com/DirtyUnicorns/android_manifest.git -b p9x
      - repo sync --force-sync -j$( nproc --all )
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Sync Completed!"

  Build_script:
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="...Building..."
      - ./collect.sh
      #- ./final.sh
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/blueline/ && ls *blueline*.zip) Completed!"

  Upload_script:
      #- curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploading Build $(cd /tmp/rom/out/target/product/blueline/ && ls *blueline*.zip)"
      #- rclone copy /tmp/rom/out/target/product/blueline/*blueline*.zip rclonerw:blueline -P
      #- curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Build $(cd /tmp/rom/out/target/product/blueline/ && ls *blueline*.zip) Uploaded Successfully!"
      #- curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Download link https://mirror.rsdclxvi.workers.dev/cirrus/blueline/$(cd /tmp/rom/out/target/product/blueline/ && ls *blueline*.zip)"
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="...Compressing ccache..."
      - ./ziping.sh
      - cd /tmp
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="...Uploading ccache...."
      - curl -s https://api.telegram.org/bot$tokentl/sendMessage -d chat_id=$idtl -d text="Uploaded Successfully!"
